### PR TITLE
fixed setfill and match

### PR DESCRIPTION
**Pull request by lafis002**
Changed the instructions that we discussed in Office Hours

### CODE REVIEW

**Comment by lafis002** [comment]
yes you are right, i changed it. Should be good now.

**Comment by joseemoreira** [comment]
How about fsub and isjki?

**Comment by joseemoreira** [comment]
I have merged other pull requests. You may want to see if those match yours.

**Comment by joseemoreira** [comment]
Lars, please check conflicting files.

**Comment by lafis002** [comment]
I merged everything, so this PR can probably be closed. I will change all the relevant instructions for my part by the end of today and open a new Pull Request (or you leave this one open).
However, the code that was pushed by someone else causes problems for me (could be mac specific): for xkj and isjkj, where we stream the displacement _k in the tracefile, it appears to be binary and cannot be displayed in a textfile.

**Comment by lafis002** [comment]
Hello Professor, I have now implemented the remaining instructions for zdrot (except for 1), I still have the problem described above with the displacement in the stringstream

**Comment by joseemoreira** [comment]
Lars,

I think you may be having a problem because of the idiosyncrasies of C++ streaming. When you stream a u08 object, it always thinks it is a character and tries to interpret the code. This causes problem. I believe an easy solution is to cast it to u32 before streaming. That will make C++ streams treat it as an integer number, not a character. Please give it a try.

I am going to close this pull request. Please reopen when you are ready.

Jose

**Pull request closed without merging**
